services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medassist
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile 
    ports:
      - "8080:80"
    environment:
      - REDIS_URL=redis://redis:6379
      - AGENT_SERVICE_URL=http://agent-service:8000
      - ANALYTICS_SERVICE_URL=http://analytics-service:8004
      - NOTIFICATION_SERVICE_URL=http://notification-service:8003
    depends_on:
      - redis

  agent-service:
    build:
      context: .
      dockerfile: services/agent-service/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/medassist
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  analytics-service:
    build:
      context: .
      dockerfile: services/analytics-service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/medassist

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/medassist
  vision-service:
    build: ./services/vision-service
    ports:
      - "8008:8008"
    volumes:
      - ./services/vision-service/model:/app/model

  voice-service:
    build: ./services/voice-service
    ports:
      - "8005:8004" #
      - "8006:8005" # 
    environment:
      - STT_DEVICE=cpu
      - TTS_DEVICE=cpu

volumes:
  postgres_data: